### ISSUE TITLE
Fix "lost-column" and "lost-offset" rule bug

### ISSUE THREAD

**Issue by 4ok** [bem-contrib/bem-grid#116]
Now used the following rule: `lost-offset: $i/12;` and `lost-column: $i/12;`, but it's not working. Lost module needed rule like that: `1/<NUM_PARTS>`.

At this time I see what all rules look like this:

```css
.row__col_sw_<1..12>:nth-child(12n) {
    margin-right: <GUTTER>;
}
```
